<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Version>1.7.0</Version>
        <Description>BetterOtherRoles</Description>
        <Authors>Brybry</Authors>
		<LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <Platforms>AnyCPU</Platforms>
        
        
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**" />
    </ItemGroup>
   
	<ItemGroup>
		<PackageReference Include="AmongUs.GameLibs.Steam" Version="2024.6.18" />
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.692" />
		<PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="UniverseLib.IL2CPP">
            <HintPath>Resources\Files\UniverseLib.IL2CPP.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    <PropertyGroup>
        <AmongUsPluginsDir Condition=" '$(AmongUsPluginsDir)' == '' ">E:\SteamLibrary\steamapps\common\Among Us - BOR-Update\BepInEx\plugins\BetterOtherRoles</AmongUsPluginsDir>
    </PropertyGroup>

    <Target Name="CopyPlugins" AfterTargets="AfterBuild"
            Condition=" Exists('$(AmongUsPluginsDir)') ">
        <Message Importance="high" Text="Deploying $(TargetFileName) -&gt; $(AmongUsPluginsDir)" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AmongUsPluginsDir)" />
    </Target>
</Project>
